#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 2.0.0.{build}

# os: WMF 5

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: echo Pass 01 - Init ------------------------
  - git config --global core.autocrlf input

# clone directory
# clone_folder: c:\projects\myproject

# fetch repository as zip archive
shallow_clone: true                 # default is "false"

# set clone depth
clone_depth: 1                      # clone entire repository history if not defined

# scripts that run after cloning repository
install:
  - cmd: echo Pass 02 - Install ---------------------
  - cmd: set
  - cmd: echo %Configuration%
  - cmd: if "%Configuration%" == "Debug"  echo DEBUG
  - cmd: if "%Configuration%" == "Release"  echo RELEASE

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform:
  - x86
#  - amd64

configuration:
  - Debug
  # - Release
  
# scripts to run before build
before_build:
  - cmd: echo Pass 03 - Before Build ----------------
  # - pwsh: ./os.ps1 -d -dev -api .
  # - pwsh: Get-ChildItem "env:"

# scripts to run *after* solution is built and *before* automatic packaging occurs (web apps, NuGet packages, Azure Cloud Services)
before_package:
  - cmd: echo Pass 04 - Before Package --------------

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cmd: echo Pass 05 - Build Script ----------------

# scripts to run after build
after_build:
  - cmd: echo Pass 06 - After Build -----------------
  - cmd: makensis.exe /INPUTCHARSET UTF8 /OUTPUTCHARSET UTF8 /DVERSION=%APPVEYOR_BUILD_VERSION% %APPVEYOR_BUILD_FOLDER%\build\windows\nsis\cmd_fw.nsi
  - cmd: call "%APPVEYOR_BUILD_FOLDER%\build\windows\cab\make.cmd" -api "%APPVEYOR_BUILD_FOLDER%"
  - cmd: makecab.exe /V4 /D VERSION=%APPVEYOR_BUILD_VERSION% /D ROOT=%APPVEYOR_BUILD_FOLDER% %APPVEYOR_BUILD_FOLDER%\build\windows\cab\cmd_fw.ddf

  # artifacts @see https://www.appveyor.com/docs/packaging-artifacts/
artifacts:
  - path: nsis/CmdFw-%APPVEYOR_BUILD_VERSION%.exe
    name: Setup
    type: File
  - path: nsis/CmdFw-%APPVEYOR_BUILD_VERSION%.cab
    name: CmdFw-%APPVEYOR_BUILD_VERSION%.cab
  
