#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 2.0.0.{build}

# os: WMF 5

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: echo Pass 01 - Init ------------------------
  - git config --global core.autocrlf input

# clone directory
# clone_folder: c:\projects\myproject

# fetch repository as zip archive
shallow_clone: true                 # default is "false"

# set clone depth
clone_depth: 1                      # clone entire repository history if not defined

# scripts that run after cloning repository
install:
  - cmd: echo Pass 02 - Install ---------------------
  - cmd: set
  - cmd: echo %Configuration%
  - cmd: if "%Configuration%" == "Debug"  echo DEBUG
  - cmd: if "%Configuration%" == "Release"  echo RELEASE

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform:
  - x86
#  - amd64

configuration:
  - Debug
  # - Release
  
# scripts to run before build
before_build:
  - cmd: echo Pass 03 - Before Build ----------------

# scripts to run *after* solution is built and *before* automatic packaging occurs (web apps, NuGet packages, Azure Cloud Services)
before_package:
  - cmd: echo Pass 04 - Before Package --------------

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cmd: echo Pass 05 - Build Script ----------------

# scripts to run after build
after_build:
  - cmd: echo Pass 06 - After Build -----------------
  - cmd: makensis.exe /INPUTCHARSET UTF8 /OUTPUTCHARSET UTF8 /DVERSION=%APPVEYOR_BUILD_VERSION% %APPVEYOR_BUILD_FOLDER%\build\windows\nsis\cmd_fw.nsi
  - cmd: makecab.exe /F "%APPVEYOR_BUILD_FOLDER%\build\windows\cab\cmd_fw.ddf" /D SourceDir=%APPVEYOR_BUILD_FOLDER% /D CabinetNameTemplate=cmdfw-%APPVEYOR_BUILD_VERSION%.cab /D DiskDirectoryTemplate=%APPVEYOR_BUILD_FOLDER%\releases

  # artifacts @see https://www.appveyor.com/docs/packaging-artifacts/
artifacts:
  - path: releases/CmdFw-%APPVEYOR_BUILD_VERSION%.exe
    name: to-publish
  - path: releases/CmdFw-%APPVEYOR_BUILD_VERSION%.cab
    name: to-publish

# see @url https://www.appveyor.com/docs/deployment/
# and @url https://www.appveyor.com/docs/deployment/github/
deploy:
  description: '$(APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED)'
  auth_token:
    secure: m+LSSJicczPadkIy5LORLVxh1eyK8Onyn0OyEDKKmXAZVlLNd/baAPeryXS/PID+
  artifact: to-publish
  appveyor_repo_tag: true        # deploy on tag push only
  provider: GitHub
  release: v%APPVEYOR_BUILD_VERSION%
  draft: false
  prerelease: true
  force_update: true
  on:
    tag: $(APPVEYOR_REPO_TAG_NAME)
    # branch: master
